### ISSUE TITLE
The issuer certificate public key algorithm does not match the value for this certificate request

### ISSUE THREAD

**Issue by Distil62** [damienbod/AspNetCoreCertificates#34]
Hello ! I want to sign a leaf certificate with a custom generated CA but I have this error 
```
System.Private.CoreLib: Exception while executing function: 
CreateLeafCert. System.Security.Cryptography.X509Certificates: The issuer certificate public key algorithm (1.2.840.113549.1.1.1)
does not match the value for this certificate request (1.2.840.10045.2.1), 
use the X509SignatureGenerator overload.
```

But i don't know what i'm supposed to changed T_T
Somone can help me ?
Thank for your help :)

**Comment by Distil62** [comment]
There is my code 

```
public static Stream GenerateLeafCert2(string subjectName, X509Certificate2 CACertificate)
        {   
            var serviceProvider = new ServiceCollection()
                .AddCertificateManager()
                .BuildServiceProvider();

            var createClientServerAuthCerts = serviceProvider.GetService<CreateCertificatesClientServerAuth>();

            var testDevice01 = createClientServerAuthCerts.NewDeviceChainedCertificate(
                new DistinguishedName { CommonName = subjectName },
                new ValidityPeriod { ValidFrom = DateTime.UtcNow, ValidTo = DateTime.UtcNow.AddYears(10) },
                subjectName, CACertificate);
            testDevice01.FriendlyName = subjectName;

            string password = "1234";
            var importExportCertificate = serviceProvider.GetService<ImportExportCertificate>();
            var deviceInPfxBytes = importExportCertificate.ExportChainedCertificatePfx(password, testDevice01, CACertificate);

            return new MemoryStream(deviceInPfxBytes);
        }
```
CACertificate is my certificate with a private key.

**Comment by willyt150** [comment]
I just ran into this same issue when attempting to call createClientServerAuthCerts.NewDeviceChainedCertificate

Any idea/news on how to fix this?

**Comment by willyt150** [comment]
@damienbod I have figured out my issue.

My intermediate cert (that's been generated by my security division for our use) is using the RSA algorithm instead of ECDsa.

I noticed that you've built out support in `CreateCertificates` for RSA. So for now in my own code I copied the public and private `NewDeviceChainedCertificate` methods from `CreateCertificatesClientServerAuth` and changed the private one to call `_createCertificates.NewRsaChainedCertificate` and then everything worked!

I'll try to get a PR up with the change to expose a `NewRsaDeviceChainedCertificate` and then you can take it, leave it, or whatever you want :)

**Comment by willyt150** [comment]
Created PR here: https://github.com/damienbod/AspNetCoreCertificates/pull/44

**Comment by damienbod** [comment]
added to version 1.0.7
